version: '2'
services:
  route53:
    image: rancher/external-dns:v0.7.7
    environment:
      AWS_ACCESS_KEY: "${AWS_ACCESS_KEY}"
      AWS_SECRET_KEY: "${AWS_SECRET_KEY}"
      NAME_TEMPLATE: '%{{service_name}}.%{{stack_name}}.%{{environment_name}}'
      ROOT_DOMAIN: nathanmalishev.com
      ROUTE53_MAX_RETRIES: '3'
      ROUTE53_ZONE_ID: ''
      TTL: '60'
    volumes:
    - /var/lib/rancher:/var/lib/rancher
    expose:
    - '1000'
    command:
    - -provider=route53
    labels:
      io.rancher.container.agent.role: external-dns
      io.rancher.container.create_agent: 'true'

  Rancher-Active-Proxy:
    image: adi90x/rancher-active-proxy
    environment:
      CRON: 0 2 * * *
      DEBUG: 'True'
      DEFAULT_EMAIL: nathan.malishev@localz.com
      DEFAULT_HOST: nathanmalishev.com
      DEFAULT_PORT: '80'
    stdin_open: true
    volumes:
    - /data/rancher-active-proxy/htpasswd:/etc/nginx/htpasswd
    - /data/rancher-active-proxy/vhost.d:/etc/nginx/vhost.d
    - /data/rancher-active-proxy/letsencrypt:/etc/letsencrypt
    tty: true
    ports:
    - 80:80/tcp
    - 443:443/tcp
    labels:
      io.rancher.container.pull_image: always

