version: '2'
services:
  Rancher-Active-Proxy:
    image: adi90x/rancher-active-proxy
    environment:
      CRON: 0 2 * * *
      DEBUG: 'True'
      DEFAULT_EMAIL: nathan.malishev@localz.com
      DEFAULT_HOST: nathanmalishev.com
      DEFAULT_PORT: '80'
    stdin_open: true
    volumes:
    - /data/rancher-active-proxy/htpasswd:/etc/nginx/htpasswd
    - /data/rancher-active-proxy/vhost.d:/etc/nginx/vhost.d
    - /data/rancher-active-proxy/letsencrypt:/etc/letsencrypt
    tty: true
    ports:
    - 80:80/tcp
    - 443:443/tcp
    labels:
      io.rancher.container.pull_image: always
      # Make wordpress a global service
      io.rancher.scheduler.global: 'true'
